services:
  db:
    image: mysql:8.0.29
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: devquest-db
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3306
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - devquest-network

  devquest-aws:
    image: msimeaor/devquest-aws
    restart: always
    env_file:
      - .env
    build: ./
    working_dir: /DevQuestAWS
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/devquest-db?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: docker
      security.jwt.token.secret-key: ${TOKEN_JWT_SECRETKEY}
      security.jwt.token.expire-length: ${TOKEN_JWT_EXPIRELENGTH}
    command: mvn spring-boot:run
    depends_on:
      - db
    ports:
      - 80:8080
    networks:
      - devquest-network

  portainer-aws:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - devquest-network

volumes:
  portainer_data:

networks:
  devquest-network:
    driver: bridge