name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Building application .jar
      env:
        TOKEN_JWT_SECRETKEY: ${{secrets.TOKEN_JWT_SECRETKEY}}
        TOKEN_JWT_EXPIRELENGTH: ${{secrets.TOKEN_JWT_EXPIRELENGTH}}
        SPRING_AI_OPENAI_API_KEY: ${{secrets.SPRING_AI_OPENAI_API_KEY}}
      working-directory: ./
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/devquest:latest ${{secrets.DOCKER_USERNAME}}/devquest:${{github.run_id}}
        docker push ${{secrets.DOCKER_USERNAME}}/devquest:latest
        docker push ${{secrets.DOCKER_USERNAME}}/devquest:${{github.run_id}}